### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by IamCage** [quietsy/homer-status#1]
* Serving Flask app 'app.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.5:5000/ (Press CTRL+C to quit)

**Comment by quietsy** [comment]
What error?
